######################################################################
#
# File name : fpga_top_wave.do
# Created on: Thu Oct 23 23:19:45 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
