######################################################################
#
# File name : fpga_top_simulate.do
# Created on: Thu Oct 23 23:21:56 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.fpga_top xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {fpga_top_wave.do}

view wave
view structure
view signals

do {fpga_top.udo}

run 1000ns
