######################################################################
#
# File name : tb_debounce_compile.do
# Created on: Fri Oct 24 22:07:01 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog  -incr -work xil_defaultlib  \
"../../../../debounce.v" \
"../../../../tb_debounce.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

