######################################################################
#
# File name : tb_debounce_simulate.do
# Created on: Fri Oct 24 22:07:02 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.tb_debounce xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_debounce_wave.do}

view wave
view structure
view signals

do {tb_debounce.udo}

run 1000ns
