######################################################################
#
# File name : tb_debounce_wave.do
# Created on: Wed Oct 22 15:33:03 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
