######################################################################
#
# File name : tb_fpga_top_config_wave.do
# Created on: Thu Oct 23 21:49:35 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
