######################################################################
#
# File name : tb_fpga_top_config_compile.do
# Created on: Sat Oct 25 01:20:06 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog  -incr -work xil_defaultlib  \
"../../../../debounce.v" \
"../../../../fpga_top.v" \
"../../../../input_synchronizer.v" \
"../../../../logic_analyzer_core.v" \
"../../../../sample_buffer.v" \
"../../../../test_signal_gen.v" \
"../../../../tb_fpga_top_config.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

