######################################################################
#
# File name : tb_fpga_top_config_compile.do
# Created on: Tue Nov 04 02:49:50 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xpm
vlib modelsim_lib/msim/xil_defaultlib

vmap xpm modelsim_lib/msim/xpm
vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog  -incr -sv -work xpm  \
"F:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"F:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom  -93 -work xpm  \
"F:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_VCOMP.vhd" \

vlog  -incr -work xil_defaultlib  \
"../../../../logic_analyzer.gen/sources_1/ip/ila/sim/ila.v" \
"../../../../../src/debounce.v" \
"../../../../../src/fpga_top.v" \
"../../../../../src/input_synchronizer.v" \
"../../../../../src/logic_analyzer_core.v" \
"../../../../../src/sample_buffer.v" \
"../../../../../src/test_signal_gen.v" \
"../../../../../sim/tb_fpga_top_config_commented.v" \

# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

