######################################################################
#
# File name : tb_fpga_top_config_simulate.do
# Created on: Tue Nov 04 02:49:58 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L xpm -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.tb_fpga_top_config xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_fpga_top_config_wave.do}

view wave
view structure
view signals

do {tb_fpga_top_config.udo}

run 1000ns
