######################################################################
#
# File name : tb_fpga_top_wave.do
# Created on: Thu Oct 23 02:10:23 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
