######################################################################
#
# File name : tb_input_synchronizer.udo
# Created on: Wed Oct 22 15:15:08 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
