######################################################################
#
# File name : tb_input_synchronizer_simulate.do
# Created on: Wed Oct 22 15:24:11 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.tb_input_synchronizer xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_input_synchronizer_wave.do}

view wave
view structure
view signals

do {tb_input_synchronizer.udo}

run 1000ns
