######################################################################
#
# File name : tb_input_synchronizer_wave.do
# Created on: Wed Oct 22 15:15:08 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
