######################################################################
#
# File name : tb_input_synchronizer_compile.do
# Created on: Wed Oct 22 15:24:10 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog  -incr -work xil_defaultlib  \
"../../../../input_synchronizer.v" \
"../../../../tb_input_synchronizer.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

