######################################################################
#
# File name : tb_logic_analyzer_core_compile.do
# Created on: Thu Oct 23 21:45:18 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog  -incr -work xil_defaultlib  \
"../../../../logic_analyzer_core.v" \
"../../../../tb_logic_analyzer_core.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

