######################################################################
#
# File name : tb_logic_analyzer_core_wave.do
# Created on: Thu Oct 23 00:32:23 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
