######################################################################
#
# File name : tb_logic_analyzer_core_simulate.do
# Created on: Thu Oct 23 21:45:23 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.tb_logic_analyzer_core xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_logic_analyzer_core_wave.do}

view wave
view structure
view signals

do {tb_logic_analyzer_core.udo}

run 1000ns
