######################################################################
#
# File name : tb_sample_buffer_compile.do
# Created on: Wed Oct 22 23:41:53 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog  -incr -work xil_defaultlib  \
"../../../../sample_buffer.v" \
"../../../../tb_sample_buffer.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

