######################################################################
#
# File name : tb_sample_buffer_simulate.do
# Created on: Wed Oct 22 23:41:57 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.tb_sample_buffer xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_sample_buffer_wave.do}

view wave
view structure
view signals

do {tb_sample_buffer.udo}

run 1000ns
