######################################################################
#
# File name : tb_sample_buffer_wave.do
# Created on: Wed Oct 22 23:41:57 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
