######################################################################
#
# File name : tb_sample_buffer.udo
# Created on: Wed Oct 22 23:41:57 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
