######################################################################
#
# File name : tb_test_signal_gen_simulate.do
# Created on: Thu Oct 23 00:21:37 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.tb_test_signal_gen xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_test_signal_gen_wave.do}

view wave
view structure
view signals

do {tb_test_signal_gen.udo}

run 1000ns
