######################################################################
#
# File name : tb_test_signal_gen_wave.do
# Created on: Thu Oct 23 00:21:37 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
