######################################################################
#
# File name : tb_test_signal_gen_compile.do
# Created on: Thu Oct 23 00:21:35 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog  -incr -work xil_defaultlib  \
"../../../../test_signal_gen.v" \
"../../../../tb_test_signal_gen.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

