######################################################################
#
# File name : tb_uart_bram_streamer_wave.do
# Created on: Wed Nov 05 19:34:26 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
