######################################################################
#
# File name : tb_uart_bram_streamer.udo
# Created on: Wed Nov 05 19:34:26 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
