######################################################################
#
# File name : tb_uart_bram_streamer_simulate.do
# Created on: Wed Nov 05 22:04:14 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L xpm -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.tb_uart_bram_streamer xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_uart_bram_streamer_wave.do}

view wave
view structure
view signals

do {tb_uart_bram_streamer.udo}

run 1000ns
