######################################################################
#
# File name : tb_uart_bram_streamer_compile.do
# Created on: Wed Nov 05 22:04:12 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xpm
vlib modelsim_lib/msim/xil_defaultlib

vmap xpm modelsim_lib/msim/xpm
vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog  -incr -sv -work xpm  \
"F:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"F:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom  -93 -work xpm  \
"F:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_VCOMP.vhd" \

vlog  -incr -work xil_defaultlib  \
"../../../../../src/sample_buffer.v" \
"../../../../../src/uart_bram_streamer.v" \
"../../../../../src/uart_tx.v" \
"../../../../../sim/tb_uart_bram_streamer.v" \

# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

